package es.deusto.model.services.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import es.deusto.model.services.database.dao.RSS;
import es.deusto.model.services.database.dao.Noticia;

import es.deusto.model.services.database.dao.RSSDao;
import es.deusto.model.services.database.dao.NoticiaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rSSDaoConfig;
    private final DaoConfig noticiaDaoConfig;

    private final RSSDao rSSDao;
    private final NoticiaDao noticiaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rSSDaoConfig = daoConfigMap.get(RSSDao.class).clone();
        rSSDaoConfig.initIdentityScope(type);

        noticiaDaoConfig = daoConfigMap.get(NoticiaDao.class).clone();
        noticiaDaoConfig.initIdentityScope(type);

        rSSDao = new RSSDao(rSSDaoConfig, this);
        noticiaDao = new NoticiaDao(noticiaDaoConfig, this);

        registerDao(RSS.class, rSSDao);
        registerDao(Noticia.class, noticiaDao);
    }
    
    public void clear() {
        rSSDaoConfig.getIdentityScope().clear();
        noticiaDaoConfig.getIdentityScope().clear();
    }

    public RSSDao getRSSDao() {
        return rSSDao;
    }

    public NoticiaDao getNoticiaDao() {
        return noticiaDao;
    }

}
